manifest:
  remotes:
    - name: dragonlock2
      url-base: https://github.com/dragonlock2

  projects:
    - name: zephyrboards
      remote: dragonlock2
      revision: 9c38f692abc22912042c8d1835eb5738b9d99edd
      import: true

  self:
    path: JABI
