manifest:
  remotes:
    - name: dragonlock2
      url-base: https://github.com/dragonlock2

  projects:
    - name: zephyrboards
      remote: dragonlock2
      revision: d61e787dff9f5567be45b2667d142ba68b2d5cf0
      import: true

  self:
    path: JABI
