manifest:
  remotes:
    - name: dragonlock2
      url-base: https://github.com/dragonlock2

  projects:
    - name: zephyrboards
      remote: dragonlock2
      revision: 4d9a0dd9a8f91e2f4447a5f5225587464281e30f
      import: true

  self:
    path: JABI
