manifest:
  remotes:
    - name: dragonlock2
      url-base: https://github.com/dragonlock2

  projects:
    - name: zephyrboards
      remote: dragonlock2
      revision: 960eb9e94249a422eaee89bcfd991771961762d3
      import: true

  self:
    path: JABI
