manifest:
  remotes:
    - name: dragonlock2
      url-base: https://github.com/dragonlock2

  projects:
    - name: zephyrboards
      remote: dragonlock2
      revision: 6ec6353e4a0f5011bf37cf389ba7e378ac1836b8
      import: true

  self:
    path: JABI
