manifest:
  remotes:
    - name: dragonlock2
      url-base: https://github.com/dragonlock2

  projects:
    - name: zephyrboards
      remote: dragonlock2
      revision: 912db0139ca1bfc6db0c629d7264d5befb2acd4e
      import: true

  self:
    path: JABI
