manifest:
  remotes:
    - name: dragonlock2
      url-base: https://github.com/dragonlock2

  projects:
    - name: zephyrboards
      remote: dragonlock2
      revision: 3d1a475bc8d3df05e728b1e0dd346f6dcffbc886
      import: true

  self:
    path: JABI
