manifest:
  remotes:
    - name: dragonlock2
      url-base: https://github.com/dragonlock2

  projects:
    - name: zephyrboards
      remote: dragonlock2
      revision: 5ff833de2dbf16184aebe9681fb6dec754e01d36
      import: true

  self:
    path: JABI
