manifest:
  remotes:
    - name: dragonlock2
      url-base: https://github.com/dragonlock2

  projects:
    - name: zephyrboards
      remote: dragonlock2
      revision: 46a55242cb4fea12bff35202d64c74d1bf9c5452
      import: true

  self:
    path: JABI
