manifest:
  remotes:
    - name: dragonlock2
      url-base: https://github.com/dragonlock2

  projects:
    - name: zephyrboards
      remote: dragonlock2
      revision: 1ab333c70089e18a40624ea4230d8df21f905b52
      import: true

  self:
    path: JABI
