manifest:
  remotes:
    - name: dragonlock2
      url-base: https://github.com/dragonlock2

  projects:
    - name: zephyrboards
      remote: dragonlock2
      revision: 06d463ef5684658b60397d58f6bd6d6bbfb8dba5
      import: true

  self:
    path: JABI
